export const Data = [
  {
    id: "1",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },

  {
    id: "2",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },

  {
    id: "3",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "5",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },

  {
    id: "6",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "7",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "8",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "9",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "10",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "11",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "12",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "13",
    status: "Competition",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "14",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },

  {
    id: "15",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },

  {
    id: "16",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "17",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },

  {
    id: "18",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "19",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "20",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
  {
    id: "21",
    status: "Volunteer",
    Orgainize: "Impact hub",
    Date: "4/5/10",
    location: "cambodia",
    view: "10k",
  },
];
